### ISSUE TITLE
Upgrading an existing ibmswtpm2 instance causes a crash

### ISSUE THREAD

**Issue by jejb** [kgoldman/ibmswtpm2#10]
The problem seems to be the NVChip file format has changed slightly, so trying to get a new instance to read an old file fails.  The way I can reproduce this is to go back to rev1332, manufacture the NVChip file, save the RSA primary in 81000001 and then upgrade to the latest git head.  The new version crashes on startup (it works fine if the NVChip file is deleted).

Since the current release is rev1332, all distributions are going to need a way to seamlessly upgrade customers with existing NVChip data (say by adding a version field to the NVChip file and converting old files on start up).

**Comment by jejb** [comment]
OK, the root cause of this seems to be rev1532 which does something to cause STATE_CLEAR_DATA and STATE_RESET_DATA to increase in size.  Since the NVChip layout is PERSISTENT_DATA; STATE_RESET_DATA; STATE_CLEAR_DATA; ORDERLY_DATA ...  Everything apart from PERSISTENT_DATA has the wrong offsets which causes a crash on startup.

**Comment by jejb** [comment]
I figured out what the problems are:

1. NVChip regions expanded; rev1332->rev1563
2. OBJECT expanded; rev1563->rev1628
3. BnGeneratePrimeForRSA uses expanded DRBG source; rev1332->rev1563
4. RsaAdjustPrimeCandidate algorithm change; rev1332->rev1563

1,2 can be one time migrated past on the fly.  3,4 would change the RSA primary derivation, so an old NVChip will still have to use the old algorithms even after it is migrated.  For this latter, I think a version area needs to be added to NVChip to identify which algorithms to use (old or new).  Fortunately both algorithms changed across the same revision so there really only needs to be two values: 0 for old and 1 for new (with room for more in case this happens again).  If an NVChip from rev1332 is encountered, it would be migrated to current and then have its version set to 0.  All other NVChip files would have version set to 1.

**Comment by kgoldman** [comment]
There is currently no expectation that the NVChip file is portable across releases. The original code was not designed for that use case.
